apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: supabase
data:
  kong.yml: |
    _format_version: "2.1"
    
    services:
      - name: auth-v1
        url: http://auth:9999/
        routes:
          - name: auth-v1-all
            strip_path: true
            paths:
              - /auth/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - anon
                - authenticated
                - service_role
      
      - name: rest-v1
        url: http://rest:3000/
        routes:
          - name: rest-v1-all
            strip_path: true
            paths:
              - /rest/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: true
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - anon
                - authenticated
                - service_role
      
      - name: graphql-v1
        url: http://localhost:8080/graphql/v1
        routes:
          - name: graphql-v1-all
            strip_path: true
            paths:
              - /graphql/v1
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: true
          - name: request-transformer
            config:
              add:
                headers:
                  - Content-Profile:graphql_public
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - anon
                - authenticated
                - service_role
      
      - name: realtime-v1
        url: http://realtime:4000/socket/
        routes:
          - name: realtime-v1-all
            strip_path: true
            paths:
              - /realtime/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - anon
                - authenticated
                - service_role
      
      - name: storage-v1
        url: http://storage:5000/
        routes:
          - name: storage-v1-all
            strip_path: true
            paths:
              - /storage/v1/
        plugins:
          - name: cors
    
    consumers:
      - username: anon
        keyauth_credentials:
          - key: ${ANON_KEY}
        acls:
          - group: anon
      
      - username: service_role
        keyauth_credentials:
          - key: ${SERVICE_ROLE_KEY}
        acls:
          - group: service_role
    
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          credentials: true
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            - HEAD
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
            - Apikey
          exposed_headers:
            - X-Auth-Token
          max_age: 3600

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: supabase
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:3.5
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: "/kong/kong.yml"
        - name: KONG_DNS_ORDER
          value: "LAST,A,CNAME"
        - name: KONG_LOG_LEVEL
          value: "info"
        - name: KONG_PLUGINS
          value: "cors,key-auth,acl,request-transformer"
        - name: KONG_NGINX_HTTP_INCLUDE
          value: "/kong/nginx-kong.conf"
        - name: ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-keys
              key: anon-key
        - name: SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-keys
              key: service-role-key
        ports:
        - name: kong-proxy
          containerPort: 8000
        - name: kong-admin
          containerPort: 8001
        volumeMounts:
        - name: kong-config
          mountPath: /kong
        livenessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: kong-config
        configMap:
          name: kong-config
      tolerations:
      - key: "supabase"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: supabase
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - name: kong-proxy
    port: 8000
    targetPort: 8000
  - name: kong-admin
    port: 8001
    targetPort: 8001
  selector:
    app: kong